ARG GO_VERSION=1.13.15
ARG GO_IMAGE=golang:${GO_VERSION}

FROM --platform=${BUILDPLATFORM} ${GO_IMAGE} AS go

FROM --platform=${BUILDPLATFORM} ubuntu:18.04 AS build
RUN apt-get update && apt-get install -y  \
	cmake \
	dh-apparmor \
	dh-exec \
	git \
	libapparmor-dev \
	btrfs-tools \
	libdevmapper-dev \
	libltdl-dev \
	libsystemd-dev \
	pkg-config
WORKDIR /go/src/github.com/docker/docker
ARG REPO=https://github.com/moby/moby.git
RUN git clone --branch=20.10 --depth=1 ${REPO} .
RUN --mount=src=build.sh,target=/tmp/build.sh \
	--mount=from=go,src=/usr/local/go,target=/usr/local/go \
	PATH="/usr/local/go/bin:${PATH}" GOPATH=/go OUTPUT=/tmp/build /tmp/build.sh

FROM scratch as binary
COPY --from=build /tmp/build/* /bin/
COPY --from=build /go/src/github.com/docker/docker /src/moby