ARG GO_VERSION=1.15.6
ARG GO_IMAGE=golang:${GO_VERSION}

FROM --platform=${BUILDPLATFORM} ${GO_IMAGE} AS go

FROM --platform=${BUILDPLATFORM} ubuntu:18.04 AS build
RUN apt-get update && apt-get install -y  \
	dh-apparmor \
	dh-exec \
	git \
	libapparmor-dev \
	btrfs-tools \
	libdevmapper-dev \
	libltdl-dev \
	libsystemd-dev \
	pkg-config
WORKDIR /go/src/github.com/containerd/containerd
ARG CONTAINERD_REPO=https://github.com/containerd/containerd.git
RUN git clone --depth=1 ${CONTAINERD_REPO} .
# v1.5-beta.4
ARG CONTAINERD_COMMIT=6636e36182504789fe05f7127956bac01f6e0784
RUN if [ -n "${CONTAINERD_COMMIT}" ]; then git fetch origin "${CONTAINERD_COMMIT}" && git checkout "${CONTAINERD_COMMIT}"; fi
RUN	--mount=from=go,src=/usr/local/go,target=/usr/local/go \
	PATH="/usr/local/go/bin:${PATH}" GOPATH=/go make binaries

FROM scratch as binary
COPY --from=build /go/src/github.com/containerd/containerd/bin/* /bin/