ARG GO_VERSION=1.13.15
ARG GO_IMAGE=golang:${GO_VERSION}

FROM --platform=${BUILDPLATFORM} ${GO_IMAGE} AS go

FROM --platform=${BUILDPLATFORM} ubuntu:18.04 AS build
RUN apt-get update && apt-get install -y  \
	gcc \
	git \
	make
WORKDIR /go/src/github.com/docker/cli
ARG CLI_REPO=https://github.com/docker/cli.git
RUN git clone --branch=20.10 --depth=1 ${CLI_REPO} .
# v20.10.5
ARG CLI_COMMIT=55c4c88966a912ddb365e2d73a4969e700fc458f
RUN if [ -n "${CLI_COMMIT}" ]; then git fetch origin "${CLI_COMMIT}" && git checkout "${CLI_COMMIT}"; fi
ENV DISABLE_WARN_OUTSIDE_CONTAINER=1
RUN	--mount=from=go,src=/usr/local/go,target=/usr/local/go \
	PATH="/usr/local/go/bin:${PATH}" GOPATH=/go make dynbinary

FROM scratch as binary
COPY --from=build /go/src/github.com/docker/cli/build/docker /bin/