ARG GO_VERSION=1.13.15
ARG GO_IMAGE=golang:${GO_VERSION}

FROM --platform=${BUILDPLATFORM} ${GO_IMAGE} AS go

FROM --platform=${BUILDPLATFORM} ubuntu:18.04 AS build
RUN apt-get update && apt-get install -y  \
	gcc \
	git \
	libltdl-dev \
	make
WORKDIR /src
ARG CLI_REPO=https://github.com/docker/cli.git
RUN git clone --depth=1 ${CLI_REPO} .
# v17.06.2
ARG CLI_COMMIT=eedf92a47a266e9bcffbfc560d369160133cb8b9
RUN if [ -n "${CLI_COMMIT}" ]; then git fetch origin "${CLI_COMMIT}" && git checkout "${CLI_COMMIT}"; fi
ENV DISABLE_WARN_OUTSIDE_CONTAINER=1
ENV VERSION=17.06.2
RUN	--mount=from=go,src=/usr/local/go,target=/usr/local/go \
	mkdir -p /go/src/github.com/docker/; \
	set -e; mv components/cli /go/src/github.com/docker/cli; cd /go/src/github.com/docker/cli ; PATH="/usr/local/go/bin:${PATH}" GOPATH=/go make dynbinary

FROM scratch as binary
COPY --from=build /go/src/github.com/docker/cli/build/docker /bin/