ARG GO_VERSION=1.13.15
ARG GO_IMAGE=golang:${GO_VERSION}

FROM --platform=${BUILDPLATFORM} ${GO_IMAGE} AS go

FROM --platform=${BUILDPLATFORM} ubuntu:18.04 AS build
RUN apt-get update && apt-get install -y \
	git \
	libseccomp-dev \
	make \
	pkg-config
WORKDIR /go/src/github.com/opencontainers/runc
ARG RUNC_REPO=https://github.com/opencontainers/runc.git
RUN git clone --depth=1 ${RUNC_REPO} .
# v1.0.0-rc93
ARG RUNC_COMMIT=12644e614e25b05da6fd08a38ffa0cfe1903fdec
RUN if [ -n "${RUNC_COMMIT}" ]; then git fetch origin "${RUNC_COMMIT}" && git checkout "${RUNC_COMMIT}"; fi
RUN \
	--mount=from=go,src=/usr/local/go,target=/usr/local/go \
	PATH="/usr/local/go/bin:${PATH}" make runc BUILDTAGS='seccomp apparmor selinux'


FROM scratch AS binary
COPY --from=build /go/src/github.com/opencontainers/runc/runc /bin/
