
name: Cache Builder
on:
  workflow_dispatch:
jobs:
  artifacts-cache:
    name: Build Cache
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            project: runc
            version: "1.0"
          - os: ubuntu-20.04
            project: runc
            version: "master"
          - os: ubuntu-20.04
            project: containerd
            version: "1.4"
          - os: ubuntu-20.04
            project: containerd
            version: "1.5"
          - os: ubuntu-20.04
            project: engine
            version: "20.10"
          - os: ubuntu-20.04
            project: engine
            version: master
          - os: ubuntu-20.04
            project: cli
            version: "20.10"
          - os: ubuntu-20.04
            project: cli
            version: "19.03"
          - os: ubuntu-20.04
            project: cli
            version: "master"
          - os: ubuntu-18.04
            project: runc
            version: "1.0"
          - os: ubuntu-18.04
            project: runc
            version: "master"
          - os: ubuntu-18.04
            project: containerd
            version: "1.4"
          - os: ubuntu-18.04
            project: containerd
            version: "1.5"
          - os: ubuntu-18.04
            project: engine
            version: "20.10"
          - os: ubuntu-18.04
            project: engine
            version: master
          - os: ubuntu-18.04
            project: cli
            version: "20.10"
          - os: ubuntu-18.04
            project: cli
            version: "19.03"
          - os: ubuntu-18.04
            project: cli
            version: "master"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        if: ${{ matrix.version == 'master' }} && ${{ matrix.project == 'engine' }}
        with:
          repository: moby/moby
          fetch-depth: 1
          path: moby-src
      - name: Setup buildx instance
        uses: docker/setup-buildx-action@v1
        with:
          use: true
      - name: Login to GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        env:
          NO_OUTPUT: 1
          VERSION: ${{matrix.version}}
          DISTRO: ${{matrix.os}}
        run: |
          set -e -x

          tag=${{matrix.project}}-$(echo ${{matrix.os}}${{matrix.version}} | sha256sum | awk '{{ print $1 }}')
          export CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${tag}"
          export CACHE_TO="${CACHE_FROM}"

          if [ "${{matrix.project}}" = "engine" ] && [ "${VERSION}" = "master" ]; then
            export ENGINE_COMMIT="$(git -C ./moby-src rev-parse HEAD)"
          fi

          make -j 4 ${{matrix.project}}
  runner-cache:
    name: Build Cache
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-18.04"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup buildx instance
        uses: docker/setup-buildx-action@v1
        with:
          use: true
      - name: Login to GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        env:
          APT_MIRROR: http://azure.archive.ubuntu.com/ubuntu
          CACHE_FROM: ghcr.io/${{github.repository}}/${{matrix.os}}:latest
          CACHE_TO: ghcr.io/${{github.repository}}/${{matrix.os}}:latest
        run: docker buildx build --cache-from "${CACHE_FROM}" --cache-to "${CACHE_TO}" -< Dockerfile.${{ matrix.os }}