name: Integration
on:
  workflow_dispatch:

jobs:
  integration-linux:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-18.04"]
        engine: ["20.10"]
        containerd: ["1.4"]
        runc: ["1.0"]
        cli: ["20.10", "19.03"]
    steps:
    - name: Install go
      uses: actions/setup-go@v2
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libseccomp2
    - uses: actions/checkout@v2
    - name: Build all the things
      run: |
        set -e -x
        make engine VERSION="${{ matrix.engine }}"
        make cli VERSION="${{ matrix.cli }}"
        make containerd VERSION="${{ matrix.containerd }}"
        make runc VERSION="${{ matrix.runc }}"
        mkdir -p ~/go/src/github.com/docker
        mv out/src/moby ~/go/src/github.com/docker/docker
    - name: Test
      run: |
        export GOPATH=~/go
        export PATH="$(pwd)/out/bin:${PATH}"
        cd ~/go/src/github.com/docker/docker
        hack/make.sh test-integration