name: Integration
on:
  workflow_dispatch:

jobs:
  integration-linux:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-18.04"]
        engine: ["20.10"]
        containerd: ["1.4"]
        runc: ["1.0"]
        cli: ["20.10", "19.03"]
    steps:
    - name: Install go
      uses: actions/setup-go@v2
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y libseccomp2
    - uses: actions/checkout@v2
    - name: Setup buildx instance
      uses: docker/setup-buildx-action@v1
      with:
        use: true
    - name: Login to GHCR
      run: echo ${{ secrets.CR_PAT }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build all the things
      env:
        DISTRO: ${{matrix.os}}
      run: |
        set -e -x

        engine_tag="$(echo ${{matrix.os}}${{matrix.engine}} | sha256sum | awk '{{ print $1 }}')"
        cli_tag="$(echo ${{matrix.os}}${{matrix.cli}} | sha256sum | awk '{{ print $1 }}')"
        containerd_tag="$(echo ${{matrix.os}}${{matrix.containerd}} | sha256sum | awk '{{ print $1 }}')"
        runc_tag="$(echo ${{matrix.os}}${{matrix.runc}} | sha256sum | awk '{{ print $1 }}')"

        make engine VERSION="${{ matrix.engine }}" CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${engine_tag}" CACHE_TO="ghcr.io/${{ github.repository }}/cache:${engine_tag}"
        make cli VERSION="${{ matrix.cli }}" CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${cli_tag}" CACHE_TO="ghcr.io/${{ github.repository }}/cache:${cli_tag}"
        make containerd VERSION="${{ matrix.containerd }}" CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${containerd_tag}" CACHE_TO="ghcr.io/${{ github.repository }}/cache:${containerd_tag}"
        make runc VERSION="${{ matrix.runc }}" CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${runc_tag}" CACHE_TO="ghcr.io/${{ github.repository }}/cache:${runc_tag}"
        mkdir -p ~/go/src/github.com/docker
    - name: Test
      env:
        DOCKER_INTEGRATION_TESTS_VERIFIED: true
      run: |
        set -e
        sudo systemctl stop docker
        sudo systemctl stop containerd
        make test