name: Integration
on:
  workflow_dispatch:
    inputs:
      testFilter:
        description: Run a subset of tests(TEST_FILTER)
        default: ''

jobs:
  integration-linux:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "ubuntu-18.04"]
        engine: ["20.10"]
        containerd: ["1.4"]
        runc: ["1.0"]
        cli: ["20.10", "19.03"]
    steps:
    - uses: actions/checkout@v2
    - name: Login to GHCR
      run: echo ${{ secrets.CR_PAT }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build all the things
      env:
        DISTRO: ${{matrix.os}}
        ENGINE_VERSION: ${{matrix.engine}}
        CLI_VERSION: ${{matrix.cli}}
        RUNC_VERSION: ${{matrix.runc}}
        CONTAINERD_VERSION: ${{matrix.containerd}}
      run: |
        set -e -x

        engine_tag="engine-$(echo ${{matrix.os}}${{matrix.engine}} | sha256sum | awk '{{ print $1 }}')"
        cli_tag="cli-$(echo ${{matrix.os}}${{matrix.cli}} | sha256sum | awk '{{ print $1 }}')"
        containerd_tag="containerd-$(echo ${{matrix.os}}${{matrix.containerd}} | sha256sum | awk '{{ print $1 }}')"
        runc_tag="runc-$(echo ${{matrix.os}}${{matrix.runc}} | sha256sum | awk '{{ print $1 }}')"

        export ENGINE_CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${engine_tag}"
        export CLI_CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${cli_tag}"
        export CONTAINERD_CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${containerd_tag}"
        export RUNC_CACHE_FROM="ghcr.io/${{ github.repository }}/cache:${runc_tag}"

        make -j 4 engine cli containerd runc
    - name: Test
      env:
        DOCKER_INTEGRATION_TESTS_VERIFIED: true
        APT_MIRROR: http://azure.archive.ubuntu.com/ubuntu
        CACHE_FROM: ghcr.io/${{github.repository}}/${{matrix.os}}:latest
        TEST_FILTER: ${{ github.event.inputs.testFilter }}
      run: make test DISTRO=${{matrix.os}}
    - uses: actions/upload-artifact@v2
      if: failure() || cancelled()
      with:
        name: os=${{ matrix.os }} engine=${{ matrix.engine }} containerd=${{ matrix.containerd }} cli=${{ matrix.cli }} runc=${{ matrix.runc }}
        path: |
          out/tests/**
          !out/tests/**/root
        retention-days: 1
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: out/tests/test-integration/*.xml
        report_individual_runs: true